apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: shared-kiali-authz-policy
  namespace: {{ .Values.istio.namespace }}
spec:
  action: ALLOW
  {{- if not .Values.istio.clusterWideHardenedEnabled }}
  selector:
    matchLabels:
      {{ .Values.selector.key | default "protect" }}: {{ .Values.selector.value | default "keycloak" | quote }}
  {{- end }}
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.kiali.namespaces | toYaml | nindent 8 }}
        principals: {{ .Values.istio.hardened.kiali.principals | toYaml | nindent 8 }}
    to:
    - operation:
        methods:
        - GET
        - POST
        paths:
        - /*
