apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-authn
  namespace: istio-system
spec:
  selector:
    matchLabels:
      {{ .Values.selector.key | default "protect" }}: {{ .Values.selector.value | default "keycloak" | quote }}
  jwtRules:
    {{- if .Values.issuer_uri }}
    - issuer: {{ .Values.issuer_uri }}
    {{- else }}
    - issuer: https://{{ .Values.global.oidc.host }}/auth/realms/{{ .Values.global.oidc.realm }}
    {{- end }}
    {{- if .Values.global.jwks }}
      jwks: {{ .Values.global.jwks | quote }}
    {{- else if .Values.jwks_uri }}
      jwksUri: {{ .Values.jwks_uri}}
    {{- else }}
      jwksUri: https://{{ .Values.global.oidc.host }}/auth/realms/{{ .Values.global.oidc.realm }}/protocol/openid-connect/certs
    {{- end }}
      forwardOriginalToken: true
