apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authservice-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authservice-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: authservice-secrets
subjects:
  - kind: ServiceAccount
    name: {{ include "authservice.serviceAccountName" . }}