apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authservice.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authservice.labels" . | nindent 4 }}
stringData:
  config.json: |
    {
      "listen_address": "0.0.0.0",
      "listen_port": "{{ .Values.service.port }}",
      "log_level": "{{ .Values.config.logLevel }}",
      "default_oidc_config": {
        {{- if and $.Values.global.authorization_uri $.Values.global.token_uri }}
        "authorization_uri": "{{ $.Values.global.authorization_uri }}",
        "token_uri": "{{ $.Values.global.token_uri }}",
        {{- else }}
        "authorization_uri": "https://{{ $.Values.global.oidc.host }}/auth/realms/{{ $.Values.global.oidc.realm }}/protocol/openid-connect/auth",
        "token_uri": "https://{{ $.Values.global.oidc.host }}/auth/realms/{{ $.Values.global.oidc.realm }}/protocol/openid-connect/token",
        {{- end }}
        "jwks": {{ $.Values.global.jwks | quote }},
        "client_id": "{{ $.Values.global.client_id }}",
        "client_secret": "{{ $.Values.global.client_secret }}",
        "cookie_name_prefix": "{{ $.Values.global.cookie_name_prefix }}",
        "id_token": {
          "preamble": "Bearer",
          "header": "Authorization"
        },
        "access_token": {
          "header": "JWT"
        },
        {{- if contains "\\n" $.Values.global.certificate_authority }}
        "trusted_certificate_authority": "{{ $.Values.global.certificate_authority }}",
        {{- else }}
        "trusted_certificate_authority": {{ $.Values.global.certificate_authority | quote }},
        {{- end }}
        "logout": {
          "path": "{{ $.Values.global.logout_path }}"{{ if $.Values.global.logout_redirect_uri }},
          "redirect_uri": "{{ $.Values.global.logout_redirect_uri }}"
          {{- else if $.Values.global.oidc }},
          "redirect_uri": "https://{{ $.Values.global.oidc.host }}/auth/realms/{{ $.Values.global.oidc.realm}}/protocol/openid-connect/token/logout"
          {{- end }}
        },
        "scopes": []
      },
      "threads": 8,
      "chains": [
      {{- range $k, $v := $.Values.chains }}{{ if ne $k ( first (keys $.Values.chains | sortAlpha) ) }},{{ end }}
        {
          "name": "{{ $k }}",
          "match": {
            {{- if .match }}
            "header": "{{ .match.header | default $.Values.global.match.header }}",
            "prefix": "{{ .match.prefix | default $.Values.global.match.prefix }}"
            {{- else }}
            "header": "{{ $.Values.global.match.header }}",
            "prefix": "{{ $.Values.global.match.prefix }}"
            {{- end }}
          },
          "filters": [
            {
              "oidc_override": {
                {{- if and .authorization_uri .token_uri }}
                "authorization_uri": "{{ .authorization_uri }}",
                "token_uri": "{{ .token_uri }}",
                {{- else if .oidc }}
                "authorization_uri": "https://{{ .oidc.host | default $.Values.global.oidc.host }}/auth/realms/{{.oidc.realm | default $.Values.global.oidc.realm }}/protocol/openid-connect/auth",
                "token_uri": "https://{{ .oidc.host | default $.Values.global.oidc.host }}/auth/realms/{{ .oidc.realm | default $.Values.global.oidc.realm }}/protocol/openid-connect/token",
                {{- end}}
                {{- if or .redis_server_uri $.Values.global.redis_server_uri }}
                "redis_session_store_config": {
                  "server_uri": {{ .redis_server_uri | default $.Values.global.redis_server_uri | quote }}
                },
                {{- end }}
                {{- if .callback_uri }}
                "callback_uri": "{{ .callback_uri | default $.Values.callback_uri }}",
                {{- else }}
                {{- fail "ERROR: Missing required field 'callback_uri' in one of the config chains" }}
                {{ end }}
                {{- if .jwks }}
                "jwks": {{ .jwks | quote }},
                {{- end }}
                {{- if .client_id }}
                "client_id": "{{ .client_id }}",
                {{- end }}
                {{- if .client_secret }}
                "client_secret": "{{ .client_secret }}",
                {{- end }}
                {{- if .cookie_name_prefix }}
                "cookie_name_prefix": "{{ .cookie_name_prefix }}",
                {{- end }}
                {{- if .certificate_authority }}
                {{- if contains "\\n" .certificate_authority }}
                "trusted_certificate_authority": "{{ .certificate_authority }}",
                {{- else }}
                "trusted_certificate_authority": {{ .certificate_authority | quote }},
                {{- end }}
                {{- end }}
                "logout": {
                {{- if .logout_path }}
                  "path": "{{ .logout_path | default $.Values.global.logout_path }}",
                {{- end }}
                {{- if .logout_redirect_uri }}
                  "redirect_uri": "{{ .logout_redirect_uri | default $.Values.global.logout_redirect_uri }}"
                {{- else if .oidc }}
                  "redirect_uri": "https://{{ .oidc.host | default $.Values.global.oidc.host }}/auth/realms/{{ .oidc.realm | default $.Values.global.oidc.realm}}/protocol/openid-connect/token/logout"
                {{- else }}
                  "redirect_uri": "https://{{ $.Values.global.oidc.host }}/auth/realms/{{ $.Values.global.oidc.realm }}/protocol/openid-connect/token/logout"
                {{- end}}
                },
                "scopes": []
              }
            }
          ]
        }
      {{- end }}
      ]
    }
