apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authservice.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authservice.labels" . | nindent 4 }}
stringData:
  config.json: |
    {
      "listen_address": "0.0.0.0",
      "listen_port": "{{ .Values.service.port }}",
      "log_level": "{{ .Values.config.logLevel }}",
      "threads": 8,
      "chains": [
      {{- range $k, $v := $.Values.chains }}{{ if ne $k ( first (keys $.Values.chains | sortAlpha) ) }},{{ end }}
        {
          "name": "{{ $k }}",
          "match": {
            {{- if .match }}
            "header": "{{ .match.header | default $.Values.global.match.header }}",
            "prefix": "{{ .match.prefix | default $.Values.global.match.prefix }}"
            {{- else }}
            "header": "{{ $.Values.global.match.header }}",
            "prefix": "{{ $.Values.global.match.prefix }}"
            {{- end }}
          },
          "filters": [
            {
              "oidc": {
                {{- if .oidc }}
                "authorization_uri": "https://{{ .oidc.host | default $.Values.global.oidc.host }}/auth/realms/{{.oidc.realm | default $.Values.global.oidc.realm }}/protocol/openid-connect/auth",
                "token_uri": "https://{{ .oidc.host | default $.Values.global.oidc.host }}/auth/realms/{{ .oidc.realm | default $.Values.global.oidc.realm }}/protocol/openid-connect/token",
                {{- else }}
                "authorization_uri": "https://{{ $.Values.global.oidc.host }}/auth/realms/{{ $.Values.global.oidc.realm }}/protocol/openid-connect/auth",
                "token_uri": "https://{{ $.Values.global.oidc.host }}/auth/realms/{{ $.Values.global.oidc.realm }}/protocol/openid-connect/token",
                {{- end}}
                "callback_uri": "{{ .callback_uri | default $.Values.callback_uri }}",
                "jwks": {{ .jwks | default $.Values.global.jwks | quote }},
                "client_id": "{{ .client_id | default $.Values.global.client_id }}",
                "client_secret": "{{ .client_secret | default $.Values.global.client_secret }}",
                "scopes": [],
                "cookie_name_prefix": "{{ .cookie_name_prefix | default $.Values.global.cookie_name_prefix }}",
                "id_token": {
                  "preamble": "Bearer",
                  "header": "Authorization"
                },
                "access_token": {
                  "header": "JWT"
                },
                "trusted_certificate_authority": "{{ .certificate_authority | default $.Values.global.certificate_authority }}",
                "logout": {
                  "path": "{{ .logout_path | default $.Values.global.logout_path }}",
                  {{- if .oidc }}
                  "redirect_uri": "https://{{ .oidc.host | default $.Values.global.oidc.host }}/auth/realms/{{ .oidc.realm | default $.Values.global.oidc.realm}}/protocol/openid-connect/token/logout"
                  {{- else }}
                  "redirect_uri": "https://{{ $.Values.global.oidc.host }}/auth/realms/{{ $.Values.global.oidc.realm }}/protocol/openid-connect/token/logout"
                  {{- end}} 
                }
              }
            }
          ]
        }
      {{- end }}
      ]
    }
