apiVersion: v1
kind: Service
metadata:
  name: {{ include "authservice.fullname" . }}
  labels:
    {{- include "authservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 10003
      protocol: TCP
      name: grpc
  selector:
    {{- include "authservice.selectorLabels" . | nindent 4 }}
