{{- if .Values.istio.mtls }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: default-authservice
  namespace: {{ .Release.Namespace}}
spec:
  mtls:
    mode: STRICT
{{- end }}