{{- /* Render Istio ServiceEntries */ -}}
{{- $jwks_uri := default .Values.global.jwks_uri .Values.jwks_uri }}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled $jwks_uri (not (contains .Values.global.oidc.host $jwks_uri)) -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ .Values.global.oidc.host | replace "." "-" }}-service-entry
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
    - {{ include "authservice.hostnameFromUri" ($jwks_uri) }}
  location: MESH_EXTERNAL
  ports:
    - number: 443
      protocol: TLS
      name: https
---
{{- end -}}
