{{ if .Values.networkPolicies.enabled }}
#For kube-dns
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-to-cluster-haproxy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: haproxy
  policyTypes:
    - Egress
  egress:
  - {}
{{- end }}