{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis-to-istiod
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector:
    matchLabels:
      app: redis-bb
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: istio-controlplane
    - podSelector:
        matchLabels:
          app: istiod
{{ end }}